# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Zee Ahmed | Developer
email: zee@simplyzee.co.uk
description: > # this means to ignore newlines until "baseurl:"
  Software Engineer. Passionate about code & developer security. Addicted to learning.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://simplyzee.co.uk" # the base hostname & protocol for your site
twitter_username: zeieshanahmed
github_username:  zee-ahmed

# Build settings
markdown: kramdown
