# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Seo settings
title: Zee Ahmed | Developer
email: zee@simplyzee.co.uk
description: "Software Engineer. Passionate about code & developer security. Addicted to learning."

# Site settings
baseurl: ""
url: http://simplyzee.co.uk

# Author Settings
author:
  name: Zee Ahmed
  job: Software Engineer
  bio: Software Engineer. Passionate about code & developer security. Addicted to learning.
  thumb: /assets/img/zee.jpg
  url: http://www.simplyzee.co.uk
  github: http://github.com/zee-ahmed
  twitter: http://twitter.com/zeieshanahmed
  linkedin: https://www.linkedin.com/in/zee-ahmed-5454a547

# Build settings
permalink: /:year/:month/:day/:title/
paginate: 10
paginate_path: ":num"
markdown: kramdown
sass:
  style: expanded

gems:
  - jekyll-paginate
  - jekyll-read-more
  #- jemoji